export default {
  AUTH_USER : 'AUTH_USER',
  UNAUTH_USER : 'UNAUTH_USER',
  AUTH_ERROR : 'AUTH_ERROR',
  TRY_CONNECT : 'TRY_CONNECT',
  FETCH_DGAX: 'FETCH_DGAX',
  GET_GDAX_ACCOUNT: 'GET_GDAX_ACCOUNT',
  GET_RECEIVED_ORDER: 'GET_RECEIVED_ORDER',
  GET_OPEN_ORDER: 'GET_OPEN_ORDER',
  GET_DONE_ORDER: 'GET_DONE_ORDER',
  GET_MATCH_ORDER: 'GET_MATCH_ORDER',
  GET_CHANGE_ORDER: 'GET_CHANGE_ORDER',
  GET_MARGIN_PROFILE_UPDATE: 'GET_MARGIN_PROFILE_UPDATE'
}